### PR TITLE
[ButtonGroup] Fix Segmented Button Gap Fix

### LINKED ISSUE #3243: [new DL] Segmented buttons should not have a gap
> The reason they are shown differently in Figma today is because Figma doesn't do negative auto-layout spacing. Segmented buttons should look like this.
> 
> Screen Shot 2020-09-11 at 2 40 27 PM
> 
> I think we can want to stop connecting allll the fields though.
> 
> So instead of this:
> 
> Screen Shot 2020-09-11 at 2 41 48 PM
> 
> we would do something like this:
> 
> Screen Shot 2020-09-11 at 2 41 36 PM

### PR DESCRIPTION
**Pull request by ashwinnarayanan2001**
### WHY are these changes introduced?
Fixes https://github.com/Shopify/polaris-react/issues/3243

### WHAT is this pull request doing?
This PR is fixing the gap between segmented buttons.

After 

Button group with segmented buttons
Screen Shot 2020-09-16 at 3 10 27 PM

Filters (Some filters disabled)
Screen Shot 2020-09-16 at 3 11 16 PM

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
* [ ] For visual design changes, pinged one of @ HYPD, @ mirualves, @ sarahill, or @ ry5n to update the Polaris UI kit

### CODE REVIEW

File: src/utilities/theme/tokens.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ export const Tokens = {
   textFieldSpinnerOffset: rem('2px'),
   textFieldFocusRingOffset: rem('-4px'),
   textFieldFocusRingBorderRadius: rem('7px'),
-  buttonGroupItemSpacing: rem('2px'),
+  buttonGroupItemSpacing: rem('-1px'),
```
Comment (alex-page) [inline src/utilities/theme/tokens.ts:41]: As we are no longer using the `--p-button-group-item-spacing` variable maybe we should remove it?

Comment (kyledurand) [reply src/utilities/theme/tokens.ts:41]: Oh we were when we were pairing. Ashwin it looks like the connected filters changes didn't get pushed up

**Comment by kyledurand** [comment]
One thing I noticed when we were working on this is that the focus ring is now getting clipped when tabbing through connected items. 

[Here's a screencast at 25% speed](https://screenshot.click/screencast_2020-09-16_15-18-49.mp4)

You can see the left border of the focus ring getting clipped as focus shifts right, and vice versa when shifting left

[Here's a screencast at 100% speed](https://screenshot.click/screencast_2020-09-16_15-19-11.mp4)

Still pretty noticeable. We might be able to do some funky things with z-index when connected items are focused to fix this. I'll explore later today or tomorrow

File: src/utilities/theme/tokens.ts (hunk 1 above)
Comment (ashwinnarayanan2001) [reply src/utilities/theme/tokens.ts:41]: There were no changes for the ConnectedFilterControl component. The --p-button-group-item-spacing variable is still being used in the component. It is still necessary because it's used as a fallback (without the new design language).

Comment (alex-page) [reply src/utilities/theme/tokens.ts:41]: Thanks for the context!

**Comment by alex-page** [comment]
@ashwinnarayanan2001 this also needs to be in `polaris-rails`. If you want to ship this PR and close https://github.com/Shopify/polaris-react/issues/3243 that is all good. Just make sure an issue is made for tracking this work in rails 🚀

**Review by kyledurand — APPROVED** [review]
I just checked the focus states in the old dl and the issue is happening [there](https://screenshot.click/screencast_2020-09-21_13-54-10.mp4) as well.

I think this is fine to ship as is but we should create an issue to follow up with a fix since it's more noticeable in the new design language.
