### PR TITLE
Revert "Revert "Properly handle buttons with `aria-disabled` in focus helpers""

### LINKED ISSUE #7728: [Modal] Focus isn't trapped in the modal when the primary action is disabled
## Issue summary

If a Modal has a primary action with `disabled: true`, focus isn't trapped in the modal when tabbing over focusable elements.

## Expected behavior

Focus wraps around to the first focusable element inside the Modal when tabbing away from the last focusable element.

## Actual behavior

User can tab out of the Modal if the primary action is disabled.

https://screenshot.click/polaris-modal-broken-focus-trap.mp4

## Steps to reproduce the problem

1. Create a Modal dialog with a disabled primary action
1. Open the modal. Focus should automatically move to the first focusable item within the modal.
2. Start hitting the Tab key on your keyboard. Once the last focusable item before the disabled primary input receives focus, pressing Tab again will move focus outside of the modal to the next focusable item on the rest of the page.

## Reduced test case

[Edit Polaris Modal disabled primary action focus trap](https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-uj3hm1?fontsize=14&hidenavigation=1&theme=dark)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v10.10.1
- Browser: Chrome v107
- Device: MacBook Pro
- Operating System: macOS Ventura 13.0

### PR DESCRIPTION
**Pull request by acmertz**
Reverts #7819, restoring the original change made in #7760 to fix #7728 - with a small tweak* to avoid a downstream accessibility issue caused by the original fix.

Please see the original PR (#7819) for more details on the issue being fixed.

<details><summary>*Investigation notes:</summary>
The first version of this change simply added `:not([tabindex="-1"])` to the affected CSS selector string in JS. It was updated to include `:not([aria-disabled])` based on [this review comment](https://github.com/Shopify/polaris/pull/7760#discussion_r1026916700), but this ultimately caused some Storybook accessibility failures in CI in web and prompted the original change to be reverted.

After creating a few snapshots with variations on this change, I narrowed down the issue to being caused by the addition of `:not([aria-disabled])` to the `FOCUSABLE_SELECTOR` constant in `focus.ts`:

https://github.com/Shopify/polaris/blob/35ab232b5619b691fcfe4686d504b9b470836b2f/polaris-react/src/utilities/focus.ts#L8-L9

This caused failures like this to occur in web upon upgrading to the newest version of Polaris:

```
Error: Elements must only use allowed ARIA attributes (aria-allowed-attr)
Affected node(s):
    <div tabindex="0" aria-describedby="PolarisTooltipContent1" data-polaris-tooltip-activator="true" aria-controls="Polarispopover1" aria-owns="Polarispopover1" aria-expanded="false">
    <div tabindex="0" aria-describedby="PolarisTooltipContent5" data-polaris-tooltip-activator="true" aria-controls="Polarispopover2" aria-owns="Polarispopover2" aria-expanded="false">
    <div tabindex="0" aria-describedby="PolarisTooltipContent6" data-polaris-tooltip-activator="true" aria-controls="Polarispopover3" aria-owns="Polarispopover3" aria-expanded="false">
    <div tabindex="0" aria-describedby="PolarisTooltipContent9" data-polaris-tooltip-activator="true" aria-controls="Polarispopover4" aria-owns="Polarispopover4" aria-expanded="false">
  For help resolving this see: https://dequeuniversity.com/rules/axe/4.4/aria-allowed-attr?application=axe-puppeteer
```

It appears that the test wasn't happy with some of the ARIA attributes being added to the affected `<div>` elements. The `aria-controls`, `aria-owns`, and `aria-expanded` attributes are applied in [set-activator-attributes.ts](https://github.com/Shopify/polaris/blob/revert-7819-revert-7760-acmertz/fix-focus-helpers-disabled-buttons/polaris-react/src/components/Popover/set-activator-attributes.ts) by the Popover component, [which calls the focusNextFocusableNode() helper](https://github.com/Shopify/polaris/blob/revert-7819-revert-7760-acmertz/fix-focus-helpers-disabled-buttons/polaris-react/src/components/Popover/Popover.tsx#L171) in focus.ts.

~~I wasn't able to find the exact reason why this caused the CI failures above, but my hypothesis right now is that the original change in #7819 caused a scenario where `setActivatorAttributes()` could be called for an element which lacks a `role` that allows it to use `aria-controls`, `aria-owns`, and `aria-expanded` - but the way in which the `<Popover>` manages its activator and wrapper elements with multiple refs, `useEffect()` calls, and state variables makes this tricky to confirm (coupled with the fact that the CI failure occurred in another repository, of course).~~</details>

**Update:** The issue occurred because the selector in the original PR, `:not([aria-disabled])`, incorrectly excluded elements that had `aria-disabled="false"`. Changing the selector to `:not([aria-disabled="true"])` fixes the Storybook accessibility failure that prompted the initial revert.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState} from 'react';

import {Button, Modal, Page, Stack, TextField} from '../src';

export function Playground() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  function handleClose() {
    setIsModalOpen(false);
  }

  function noop() {}

  return (
    <Page title="Playground">
      <Button onClick={() => setIsModalOpen(true)}>Open modal</Button>
      <Button disabled>Disabled button</Button>

      <Modal
        open={isModalOpen}
        onClose={handleClose}
        title="Example modal"
        primaryAction={{
          content: 'Primary action',
          onAction: handleClose,
          disabled: true,
        }}
      >
        <Modal.Section>
          <Stack vertical>
            <p>Some content</p>
            <TextField
              onChange={noop}
              autoComplete=""
              label="Text field 1"
              value=""
            />
            <TextField
              onChange={noop}
              autoComplete=""
              label="Text field 2"
              value=""
            />
          </Stack>
        </Modal.Section>
      </Modal>
    </Page>
  );
}
```

</details>

1. Copy the above code into `Playground.tsx` and run `yarn dev`
2. Confirm that the changes in this PR fix #7728:
    1. Click "Open modal"
    2. Use the Tab key to cycle through focusable elements within the modal
    3. Confirm that focus wraps around to the beginning of the modal despite the primary action button being disabled

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/utilities/focus.ts [hunk 1]
```diff
@@ -6,9 +6,9 @@ export type MouseUpBlurHandler = (
 ) => void;
 
 const FOCUSABLE_SELECTOR =
-  'a,frame,iframe,input:not([type=hidden]):not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled),*[tabindex]';
+  'a,frame,iframe,input:not([type=hidden]):not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled):not([tabindex="-1"]),*[tabindex]';
 const KEYBOARD_FOCUSABLE_SELECTORS =
-  'a,frame,iframe,input:not([type=hidden]):not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled),*[tabindex]:not([tabindex="-1"])';
+  'a,frame,iframe,input:not([type=hidden]):not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled):not([aria-disabled]):not([tabindex="-1"]),*[tabindex]:not([tabindex="-1"])';
```
Comment (chloerice) [inline polaris-react/src/utilities/focus.ts]:
```suggestion
  'a,frame,iframe,input:not([type=hidden]):not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled):not([aria-disabled="true"]):not([tabindex="-1"]),*[tabindex]:not([tabindex="-1"])';
```

**Review by chloerice — APPROVED** [review]
🙌🏽 :shipit:

**Review by AndrewMusgrave — APPROVED** [review]
