### PR TITLE
Fix focus invariant error

### LINKED ISSUE #507: Focus attempts to use findDOMNode() when it is possibly unmounted
# Issue summary

Focus attempts to run [`findDOMNode()`](https://github.com/Shopify/polaris-react/blob/a3c2898ac4d210b2eed6b4e91fa5d7c2a8021d3e/src/components/Focus/Focus.tsx#L17-L24) in callback during `didMount`. Unfortunately, by the point this happens, the component can have become unmounted. This causes an error (for those at Shopify, here's the error in Web: https://app.bugsnag.com/shopify/shopify-web-client/errors/5ae71d22fa94dc00178c5a21?event_id=5bd8c91700309c5bd43b0000&i=sk&m=fq)

## Expected behavior

No error.

## Actual behavior

An invariant violation (http://reactjs.org/docs/error-decoder.html?invariant=188). IMO we can remove the `write()` callback stuff altogether, it's an optimization we probably never needed.

## Steps to reproduce the problem

I Haven't checked but presumably rendering a `Focus`, then setting state and unmounting it immediately would lead to this issue.

### PR DESCRIPTION
**Pull request by AndrewMusgrave**
### WHY are these changes introduced?
Resolves #507

### WHAT is this pull request doing?
Previously `Focus` had it self focusing logic in a called back passed to `write` which uses `requestAnimationFrame` under the hood. It's an unneeded optimization which was causing the calledback to be invoked after the component has unmounted causing an invariant error.

### How to 🎩

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

Check the console for errors

```jsx
/* eslint-disable */

import * as React from 'react';
import {Page, AppProvider, Focus, TextStyle} from '@shopify/polaris';

interface State {
  toggle: boolean;
}

export default class Playground extends React.Component<never, State> {
  state = {
    toggle: true,
  };

  componentDidMount() {
    this.setState({toggle: false});
  }

  render() {
    const {toggle} = this.state;

    const focusMarkup = toggle && (
      <Focus>
        <TextStyle>Polaris</TextStyle>
      </Focus>
    );

    return (
      <AppProvider>
        <Page title="Playground">{focusMarkup}</Page>
      </AppProvider>
    );
  }
}

/* eslint-enable */
```

</details>

#### Notes
* Focus is not exposed so a changelog entry is not needed

### CODE REVIEW

File: src/components/Focus/Focus.tsx [hunk 1]
```diff
@@ -10,24 +10,35 @@ export interface Props {
...
+    if (root) {
+      if (!root.querySelector('[autofocus]')) {
+        focusFirstFocusableNode(root, false);
       }
-    });
+    }
   }
 
   render() {
-    const Fragment = (React as any).Fragment;
```
Comment (AndrewMusgrave) [inline src/components/Focus/Focus.tsx]: Types for react are correct now so this can be removed
