### PR TITLE
[TextField] Fix refocus bug

### LINKED ISSUE #4670: [TextField] Refocuses input causing issues with Safari date picker
Partner is having trouble with this resource: https://polaris.shopify.com/components/forms/text-field/type - they are trying to select time for this section (first screenshot) in Safari, however it doesn't let them select it - it looks like this (second screenshot). They are using Safari version 14.1.1 (16611.2.7.1.4). Do you know why this may be happening? Thanks 

image

image

## Issue summary

Trying to pick a date or time via Safari's date picker results in a re-focus of the input which shifts the cursor to the beginning of the field. This prevents the user from adjusting the time on click

### PR DESCRIPTION
**Pull request by kyledurand**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-react/issues/4670

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useCallback, useState} from 'react';

import {Stack, TextField} from '../src';

export function Playground() {
  const [value, setValue] = useState('November');

  const handleChange = useCallback((newValue) => setValue(newValue), []);

  return (
    <Stack vertical>
      <TextField
        label="Store name"
        value={value}
        onChange={handleChange}
        autoComplete="off"
        type="date"
      />
      <TextField
        label="Store name"
        value={value}
        onChange={handleChange}
        autoComplete="off"
        type="time"
      />
      <TextField
        label="Store name"
        value={value}
        onChange={handleChange}
        autoComplete="off"
        type="datetime-local"
      />
    </Stack>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

File: src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -515,10 +516,10 @@ export function TextField({
   }
 
   function handleClick({target}: React.MouseEvent) {
-    if (containsAffix(target)) {
+    if (containsAffix(target) || isInputFocused) {
```
Comment (kyledurand) [inline src/components/TextField/TextField.tsx]: I thought this would be coming from state but it's actually a utility. I'm switching to `focus` from state and that should fix the broken test

File: src/components/TextField/TextField.tsx [hunk 2]
```diff
@@ -16,6 +16,7 @@ import {Labelled, LabelledProps, helpTextID, labelID} from '../Labelled';
 import {Connected} from '../Connected';
 import {Error, Key} from '../../types';
 import {Icon} from '../Icon';
+import {isInputFocused} from '../../utilities/is-input-focused';
```
Comment (dfmcphee) [inline src/components/TextField/TextField.tsx]: Just need to 🔥 this now

**Review by dfmcphee — APPROVED** [review]

File: src/components/TextField/TextField.tsx (hunk 2 above)
Comment (kyledurand) [reply src/components/TextField/TextField.tsx]: VS is too 🧠

File: UNRELEASED.md [hunk 3]
```diff
@@ -16,6 +16,7 @@ Use [the changelog guidelines](/documentation/Versioning%20and%20changelog.md) t
 ### Bug fixes
 
 - Fixed try-catch syntax error in `Modal` ([#4553](https://github.com/Shopify/polaris-react/pull/4553))
+- Fixed an issue with `TextField` where date time were uneditable on click ([#4671](https://github.com/Shopify/polaris-react/pull/4671))
```
Comment (kyledurand) [inline UNRELEASED.md]:
```suggestion
- Fixed an issue with `TextField` where date and time were uneditable on click ([#4671](https://github.com/Shopify/polaris-react/pull/4671))
```
