### PR TITLE
[ActionList] Fix spacing above action list title when first in mobile action menu popover

### LINKED ISSUE #5877: [Page] Responsive: Action group title is too close to the top when there are no secondary actions
## Issue summary

When a `Page` has no `secondaryActions`, but it does have have an `actionGroup` with a `title`, the title of that action group appears too close to the top of the popover menu on mobile.

## Expected behavior

There should be more space above the action group title, as when there are secondary actions like in the screenshot below.

Screen Shot 2022-05-20 at 4 48 11 PM

## Actual behavior

There is very little space above the action group title when there are no secondary actions.

Screen Shot 2022-05-20 at 4 49 42 PM

## Steps to reproduce the problem

Create a `Page` that has at least one action group with a title, but does not have any secondary actions. View on mobile and check the spacing above the first title.

## Reduced test case

https://codesandbox.io/s/wandering-cherry-9sl4qe?file=/App.js

Click the "toggle responsive preview" icon to view the mobile size and click the ellipsis to open the menu to see the issue.

## Specifications

Output of `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris`:

Paste the results here:

```bash
  System:
    OS: Linux 5.10 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (32) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 65.43 GB / 125.90 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @shopify/polaris: 9.7.0 => 9.7.0
    react: ~17.0.2 => 17.0.2
    react-dom: ~17.0.2 => 17.0.2
```

### PR DESCRIPTION
**Pull request by rmleg**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/5877

When a page has action groups but no secondary actions, there is not enough spacing above the title of the first action group in the action list popover on mobile.

I can't reproduce the problem in an `ActionList` in isolation; it only seems to be present in a `Page`.

### WHAT is this pull request doing?

There was a [previous PR](https://github.com/Shopify/polaris/pull/4355) that fixed this last August by adding a `firstSection` class to the first section of the action list using the `index` when mapping across `finalSections`. However this solution is not reliable as-is because the item at the index of `0` is not always rendered.

Instead of fixing the logic, I decided to go for a CSS solution.

First, set the `padding-top` for every action list title to the increased amount.

Then, select all titles that are in sections that are not the first section and set their `padding-top` to the smaller amount.

I had originally done this by just selecting `.Section:first-child .Title` and setting its `padding-top` to the increased amount, but that broke the case where an action list is not sectioned (has only one item in its `actionGroups` array).

#### Before this PR

The first section has a title which does not have enough spacing above it.

The first section does not have title and all spacing is correct.

#### After this PR

The first section has a title and it has enough spacing above it.

The first section does not have a title and all spacing is correct. There is no change in this scenario after this PR.

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

This can be tophatted by viewing the `Page/Page with action groups` story in Storybook at a mobile screen size and expanding the action list menu.

You can also verify this does not break the `ActionList` component in isolation by viewing the `Action list/Action list with destructive item` and `Action list/Sectioned action list` stories.

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/components/ActionList/components/Section/Section.tsx [hunk 1]
```diff
@@ -54,10 +51,7 @@ export function Section({
   );
 
   const className = section.title ? undefined : styles['Section-withoutTitle'];
-  const titleClassName = classNames(
-    styles.Title,
-    firstSection && styles.firstSectionWithTitle,
-  );
+  const titleClassName = classNames(styles.Title);
```
Comment (laurkim) [inline polaris-react/src/components/ActionList/components/Section/Section.tsx]: nit: you can get rid of this and reference it directly on line 57
`<p className={styles.Title}>...`

**Review by laurkim — APPROVED** [review]
💯

File: polaris-react/src/components/ActionList/components/Section/Section.tsx (hunk 1 above)
Comment (rmleg) [reply polaris-react/src/components/ActionList/components/Section/Section.tsx]: Good catch! updated
