### PR TITLE
[Text field] Allow min and max to accept a string

### LINKED ISSUE #1988: [TextField] Max and Min have the wrong type
## Issue summary

`min` and `max` should allow for `number|string`, not just `number`.

This prevents using `min` and `max` for a native date input, [which is allowed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#max).

### PR DESCRIPTION
**Pull request by tmlayton**
### WHY are these changes introduced?

Fixes #1988 

### WHAT is this pull request doing?

Allows `number | string`, updates the prop description

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState} from 'react';
import {Page, TextField} from '../src';

export default function Playground() {
  const [value, setValue] = useState('2008-07-22');

  return (
    <Page title="Playground">
      <TextField
        label="Any time this decade 🙄"
        value={value}
        onChange={setValue}
        type="date"
        min="2010-01-01"
        max="2019-12-31"
      />
    </Page>
  );
}

```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [x] Updated the component's `README.md` with documentation changes
* [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -432,7 +432,10 @@ class TextField extends React.PureComponent<CombinedProps, State> {
     // step / value has.
     const decimalPlaces = Math.max(dpl(numericValue), dpl(step));
 
-    const newValue = Math.min(max, Math.max(numericValue + steps * step, min));
+    const newValue = Math.min(
```
Comment (BPScott) [inline src/components/TextField/TextField.tsx]: It's neat that this now allow for doing number-like strings for max and mins (note max and min being strings `"1"` not the number `1`):

```
export default function Playground() {
  const [value, setValue] = useState('1');
  const handleChange = useCallback((newValue) => setValue(newValue), []);

  return (
    <Page title="Playground">
      <TextField
        label="thing"
        value={value}
        onChange={handleChange}
        type="number"
        min="1"
        max="10"
      />
    </Page>
  );
}

```

But it means typescript will no longer complain if you do some weird misconfiguration like setting a max to a string that can't be cast to a number e.g.

```
export default function Playground() {
  const [value, setValue] = useState('0');

  const handleChange = useCallback((newValue) => setValue(newValue), []);

  return (
    <Page title="Playground">
      <TextField
        label="thing"
        value={value}
        onChange={handleChange}
        type="number"
        min="1"
        max="2019-08-10"
      />
    </Page>
  );
}
```

In this case newValue ends up being NaN and we get console warnings. Can we add a check above this to ensure  that max and min can be cast to number and if not return without triggering onChange? Perhaps something like (thought about but not tested):

```diff
- if (onChange == null) {
+ if (onChange == null || isNaN(min)) || isNaN(min)) {
```

Comment (tmlayton) [reply src/components/TextField/TextField.tsx]: > In this case newValue ends up being NaN and we get console warnings

That’s why I prefer this approach. Otherwise, with an early return for not a number the stepper no longer works without feedback to the implementer as to why. We could handle the messaging ourselves, but that is reinventing the wheel.

I also considered `isNan` values defaulting to `Infinity` or `-Infinity` which mimics the behavior of the html number input, but that makes it harder for an implementer to debug if they say, fat-fingered `10-` or something like this.

Comment (BPScott) [reply src/components/TextField/TextField.tsx]: Cool, that makes sense
