### PR TITLE
[ResourceList] Fix heading not loading

### LINKED ISSUE #735: ResourceList header doesn't render when items is populated after initial render
# Issue summary
The `ResourceList` component will render a header under certain conditions. However, when those conditions change after initial render, the header may not appear when it should:

resource-list-header-bug

Source for the UI in the above GIF is [here](https://codesandbox.io/s/q8xm4jl71w). The GIF shows two instances of `ResourceList` with the same parameters. The first instance is initialised with an empty `items` list, which is then populated when the button is clicked. The second instance has `items` populated on initialisation. The GIF shows that the second instance renders the header, whilst the first instance does not, even after `items` has been populated.

## Expected behavior
`ResourceList` header renders when conditions (e.g. whether `items` is empty) change after initialisation.

## Actual behavior
`ResourceList` header sometimes does not when conditions change after initialisation.

## Reduced test case
Sandbox [here](https://codesandbox.io/s/qxk432myy6). The issue seems to be caused by [caching](https://github.com/Shopify/polaris-react/blob/master/src/components/ResourceList/ResourceList.tsx#L328) a reference to the initial value of `listRef.current` on initialisation and reusing that initial value throughout the component's lifetime.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v3.2.1
- Browser: Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)
- Device: MacBook Pro (Retina, 13-inch, Early 2015)
- Operating System: macOS Sierra Version 10.12.6 (16G29)

### PR DESCRIPTION
**Pull request by AndrewMusgrave**
### WHY are these changes introduced?
Fixes #735

### WHAT is this pull request doing?
Removing ref from state and make it a class property

### How to 🎩

Thank you for the playground @andrewpye

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {
  Avatar,
  Button,
  Card,
  Label,
  List,
  ResourceList,
  Select,
  TextStyle,
  Page,
} from '@shopify/polaris';

const initialItemList = [
  {
    id: 341,
    url: 'customers/341',
    name: 'Mae Jemison',
    location: 'Decatur, USA',
  },
  {
    id: 256,
    url: 'customers/256',
    name: 'Ellen Ochoa',
    location: 'Los Angeles, USA',
  },
];

export default class ResourceListExample extends React.Component {
  state = {
    selectedItems: [],
    items: [],
  };

  handleSelectionChange = (selectedItems) => {
    this.setState({selectedItems});
  };

  addItems = () => {
    this.setState({items: initialItemList});
  };

  renderItem = (item) => {
    const {id, url, name, location} = item;
    const media = <Avatar customer size="medium" name={name} />;

    return (
      <ResourceList.Item
        id={id}
        url={url}
        media={media}
        accessibilityLabel={`View details for ${name}`}
      >
        <h3>
          <TextStyle variation="strong">{name}</TextStyle>
        </h3>
        <div>{location}</div>
      </ResourceList.Item>
    );
  };

  render() {
    const resourceName = {
      singular: 'customer',
      plural: 'customers',
    };

    const {items = []} = this.state;

    const promotedBulkActions = [
      {
        content: 'Edit customers',
        onAction: () => console.log('Todo: implement bulk edit'),
      },
    ];

    const bulkActions = [
      {
        content: 'Add tags',
        onAction: () => console.log('Todo: implement bulk add tags'),
      },
      {
        content: 'Remove tags',
        onAction: () => console.log('Todo: implement bulk remove tags'),
      },
      {
        content: 'Delete customers',
        onAction: () => console.log('Todo: implement bulk delete'),
      },
    ];

    return (
      <Card title="Resource list header bug">
        <Card.Section title="When items are set in an update">
          <ResourceList
            hasMoreItems
            showHeader
            sortOptions={['asdf']}
            resourceName={resourceName}
            renderItem={this.renderItem}
            selectedItems={this.state.selectedItems}
            onSelectionChange={this.handleSelectionChange}
            promotedBulkActions={promotedBulkActions}
            bulkActions={bulkActions}
            items={items}
          />
          <Button onClick={this.addItems}>Populate list</Button>
        </Card.Section>
      </Card>
    );
  }
}
```

</details>

### CODE REVIEW

**Comment by AndrewMusgrave** [comment]
@dleroux Seems 👌 with sticky? How about you?

File: src/components/ResourceList/ResourceList.tsx [hunk 1]
```diff
@@ -323,20 +323,22 @@ export class ResourceList extends React.Component<CombinedProps, State> {
...
+      this.setLoadingPosition();
+    }
   }
 
-  componentDidUpdate(prevProps: Props) {
-    if (this.props.loading && !prevProps.loading) {
+  componentDidUpdate({loading: prevLoading, items: prevItems}: Props) {
+    if (
+      this.listRef.current &&
+      this.itemsExist() &&
```
Comment (dleroux) [inline src/components/ResourceList/ResourceList.tsx]: Curious why not just compared the props?

File: src/components/ResourceList/ResourceList.tsx [hunk 2]
```diff
@@ -323,20 +323,22 @@ export class ResourceList extends React.Component<CombinedProps, State> {
...
-      {
-        listNode: this.listRef.current,
-      },
-      () => {
-        if (this.props.loading) {
-          this.setLoadingPosition();
-        }
-      },
-    );
+    this.forceUpdate();
```
Comment (dleroux) [inline src/components/ResourceList/ResourceList.tsx]: I agree that holding the node in state may not be the best approach. Do you prefer using forceUpdate like this or maybe a boolean of `hasMounted` or `refsMounted`, something a little more explicit of its purpose?

**Comment by dleroux** [comment]
🎩 is good. UNRELEASED.md is in conflict. I had made a comment regarding forceUpdate but took it back because I see that it needs to be called on the componentDidUpdate.

File: src/components/ResourceList/ResourceList.tsx (hunk 1 above)
Comment (AndrewMusgrave) [reply src/components/ResourceList/ResourceList.tsx]: They are for the edge case where items begin as undefined and then are supplied

**Comment by AndrewMusgrave** [comment]
Yup it needs to be included in `componentDidUpdate` since items are optional :)

**Comment by robertlaurin** [comment]
Pulled the branch down and tested the playground provided in the PR description. It works as expected, looking forward to this getting merged in 👍 .

File: src/components/ResourceList/tests/ResourceList.test.tsx [hunk 3]
```diff
@@ -369,6 +369,20 @@ describe('<ResourceList />', () => {
         false,
       );
     });
+
+    it('renders on noninitial load when items are provided', () => {
```
Comment (solonaarmstrong) [inline src/components/ResourceList/tests/ResourceList.test.tsx]:
```suggestion
     it('renders on non-initial load when items are provided', () => {
```

File: src/components/ResourceList/tests/ResourceList.test.tsx [hunk 4]
```diff
@@ -369,6 +369,20 @@ describe('<ResourceList />', () => {
...
+      const resourceList = mountWithAppProvider(
+        <ResourceList
+          bulkActions={bulkActions}
+          items={[]}
+          renderItem={renderItem}
+        />,
+      );
+      expect(findByTestID(resourceList, 'ResourceList-Header')).toHaveLength(0);
```
Comment (solonaarmstrong) [inline src/components/ResourceList/tests/ResourceList.test.tsx]:
```suggestion
const resourceListHeader = findByTestID(resourceList, 'ResourceList-Header');
       expect(resourceListHeader).toHaveLength(0);
```

File: src/components/ResourceList/tests/ResourceList.test.tsx [hunk 5]
```diff
@@ -369,6 +369,20 @@ describe('<ResourceList />', () => {
...
+      resourceList.setProps({items: itemsWithID});
+      resourceList.update();
+      expect(findByTestID(resourceList, 'ResourceList-Header')).toHaveLength(1);
```
Comment (solonaarmstrong) [inline src/components/ResourceList/tests/ResourceList.test.tsx]:
```suggestion
       expect(resourceListHeader).toHaveLength(1);
```

File: src/components/ResourceList/ResourceList.tsx [hunk 6]
```diff
@@ -431,9 +432,9 @@ export class ResourceList extends React.Component<CombinedProps, State> {
     ) : null;
 
     const headerMarkup = (showHeader || needsHeader) &&
-      listNode && (
+      this.listRef.current && (
```
Comment (solonaarmstrong) [inline src/components/ResourceList/ResourceList.tsx]: I thought `listNode` had been changed to the new ref syntax quite a while ago? 😕

File: src/components/ResourceList/ResourceList.tsx [hunk 7]
```diff
@@ -343,8 +345,7 @@ export class ResourceList extends React.Component<CombinedProps, State> {
       onSortChange,
       polaris: {intl},
     } = this.props;
-    const {selectMode, loadingPosition, listNode} = this.state;
-    const itemsExist = items.length > 0;
```
Comment (solonaarmstrong) [inline src/components/ResourceList/ResourceList.tsx]: I see. I think I introduced this bug when adding `loading`. Sorry about that.

File: src/components/ResourceList/ResourceList.tsx [hunk 8]
```diff
@@ -29,15 +29,16 @@ const SMALL_SCREEN_WIDTH = 458;
...
 export interface State {
   selectMode: boolean;
   loadingPosition: number;
-  listNode: HTMLUListElement | null;
 }
 
 export interface Props {
   /** Item data; each item is passed to renderItem */
-  items: any[];
+  items: Items;
```
Comment (solonaarmstrong) [inline src/components/ResourceList/ResourceList.tsx]: Just curious, what are you fixing by using a type here?

File: src/components/ResourceList/ResourceList.tsx (hunk 7 above)
Comment (AndrewMusgrave) [reply src/components/ResourceList/ResourceList.tsx]: No worries 😄

File: src/components/ResourceList/ResourceList.tsx (hunk 8 above)
Comment (AndrewMusgrave) [reply src/components/ResourceList/ResourceList.tsx]: We use this type multiple times. We just put `any[]` every time.

File: src/components/ResourceList/tests/ResourceList.test.tsx (hunk 4 above)
Comment (AndrewMusgrave) [reply src/components/ResourceList/tests/ResourceList.test.tsx]: Cool I wasn't aware you could suggest for multiple lines!!

Comment (AndrewMusgrave) [reply src/components/ResourceList/tests/ResourceList.test.tsx]: They need to stay as separate finds since the components changed between the two searches.

Comment (solonaarmstrong) [reply src/components/ResourceList/tests/ResourceList.test.tsx]: I didn't realize `findByTestID` got different instances of the same element.

Comment (AndrewMusgrave) [reply src/components/ResourceList/tests/ResourceList.test.tsx]: `findByTestID` will find the `ReactWrapper`. However it holds the reference to the `ReactWrapper`. From my understanding `enzyme` can create a new instance. Which is what Im assuming happens when `setProps` and `update` are called.
