### PR TITLE
[Filters][TextField] Replace custom Filters input with Polaris TextField

### LINKED ISSUE #11144: [Filters] Clear button should not render if not visible
The `Filters` `SearchField` is implemented to only render the query clear button if programatically  `focused`. This is a problem because consumers who are not using `IndexFilters` and who aren't handling focus in their implementation do not give merchants UX consistent with `IndexFilters`. 

The clear button's rendering logic makes it render with 0 opacity regardless of whether `focused` is set or not. This wasn't an issue when it was build because it was the only suffix markup but it's a bug now that the loading spinner has moved into the suffix. The clear button's invisible state takes up visible space if focus is not programmatically managed using the `focused` prop and there's a query value while `loading` is `true`.

cc @gcorne

## Expected behavior

The query clear button does not render when not visible.

## Actual behavior

The query clear button renders when not visible, causing the loading spinner to appear to be positioned too far left.

Screenshot 2023-11-08 at 4 07 47 PM

## Steps to reproduce the problem

- Configure Filters without managing focus using the `focused` and `onQueryFocus` props
- Set the `loading` prop to true and type some input into the field
- The clear button will render with 0 opacity to the right of the loading spinner

## Reduced test case

[CodeSandbox](https://codesandbox.io/s/filters-clear-button-bug-c5r569)

## Suggestion

The clear button should ideally "just work" based on whether:
- There's a `value`
- The input is focused (programmatically or not)

### LINKED ISSUE #11200: [IndexTable] MWeb + Mobile Webviews have large gap above first row.
## Issue summary

We are seeing an unwanted gap above the first IndexTable row in MobileWeb + Webviews. 

Screenshot 2023-11-21 at 10 09 00
Screenshot 2023-11-21 at 10 02 24
Screenshot 2023-11-21 at 10 02 16
Screenshot 2023-11-21 at 09 48 45
Screenshot 2023-11-21 at 09 48 32
Screenshot 2023-11-21 at 09 58 24

## Expected behavior

There should not be any gap above the first row.

## Actual behavior

There is a gap above the first row on MWeb + Webviews

## Steps to reproduce the problem

1. Load Admin in Chrome
2. Set Viewport to a MobileViewport
3. Visit these areas in Admin Web
  - Orders > Orders
  - Orders > Drafts
  - Content > Files
  - Products > Products
  - Products > Collections
  - Products > Transfers
  - Products > Purchase Orders

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12.1.1
- Browser: Chrome, Safari, Mobile Safari
- Device: Desktop, iOS, Android
- Operating System: mac

### PR DESCRIPTION
**Pull request by sophschneider**
Fixes https://github.com/Shopify/polaris-internal/issues/1241
Fixes https://github.com/Shopify/polaris/issues/11144
Fixes https://github.com/Shopify/web/issues/108834
Fixes https://github.com/Shopify/polaris/issues/11200

Spin to tophat (make sure no `IndexFilter` regressions): https://admin.web.filters.sophie-schneider.us.spin.dev/store/shop1/orders

On [Storybook](https://5d559397bae39100201eedc1-bqdkhjmudb.chromatic.com/?path=/story/all-components-filters--with-a-resource-list), you can tophat `Filters`, `IndexFilters` and `TextField`

### 1. Add `SearchMinor` prefix to `Filters` (and `IndexFilters`) search field

As per this [QC issue](https://github.com/Shopify/web/issues/108834) and requests from other teams using `Filters`, 

Screenshot 2023-11-21 at 4 33 01 PM

### 2. Replace custom `Filters` input with Polaris `TextField`

Custom input implementation in `Filters` caused a style divergence. This PR replaces the custom input with the Polaris `TextField`

|Before|After|
|-|-|
|Screenshot 2023-11-21 at 4 44 35 PM|Screenshot 2023-11-23 at 9 48 35 AM|

### 3. Add `size='slim'` to `TextField`

Extends `TextField` to accommodate for text field inputs in tables (which are currently custom). We should be using our own components within our other components.

@Shopify/polaris-team lmk if this api choice is ok. We could also create a new boolean prop called `inTable` or something to make the use case more specific and use it with `variant='borderless'`.

|Option 1|Option 2|Option 3|
|-|-|-|
|`<TextField variant='borderless' size='slim' />`|`<TextField variant='borderless' inTable />`|Keep custom text field implementation in `Filters`|

Note `Filters` search field height:
|-|medium and up screens|small screens|
|-|-|-|
|[Production](https://storybook.polaris.shopify.com/?path=/story/all-components-filters--with-a-resource-list)|`28px`|`28px`|
|[Figma](https://www.figma.com/file/jLLkmo9r28hiqPvf4s90E4/Polaris-Gen-3-Components?type=design&node-id=67128%3A21676&mode=design&t=0yMmrHC8rlYKmHQq-1)|`28px`|`36px`|
|This PR|`28px`|`28px`|

@Shopify/polaris-designers  I've matched this PR to production (`28px` height on small screens for `slim`). If we decide to go with this we should update figma. Otherwise, let me know and I can modify the height on this PR for small screen sizes

### 4. Fix clear button invisible rendering
[Issue for context](https://github.com/Shopify/polaris/issues/11144)

|Before|After|
|-|-|
|Screen Recording 2023-11-21 at 5 04 49 PM|Screen Recording 2023-11-21 at 5 03 34 PM|

### 5. Fix some mobile bugs
|Before|After|
|-|-|
|Screenshot 2023-11-23 at 3 22 32 PM|Screenshot 2023-11-23 at 3 22 40 PM|

|Before|After|
|-|-|
|Screenshot 2023-11-23 at 3 10 31 PM|Screenshot 2023-11-23 at 3 59 09 PM|

|Before|After|
|-|-|
|Screenshot 2023-11-23 at 4 00 35 PM|Screenshot 2023-11-23 at 4 01 12 PM|

### CODE REVIEW

File: polaris-react/src/components/Filters/components/SearchField/SearchField.tsx [hunk 1]
```diff
@@ -35,19 +33,14 @@ export function SearchField({
...
   const id = useId();
-  const inputRef = useRef<HTMLInputElement>(null);
   function handleChange(value: string) {
     onChange(value);
   }
 
-  useEffect(() => {
-    if (focused) inputRef.current?.focus();
-  }, [focused]);
-
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/components/SearchField/SearchField.tsx:50]: this logic also lives in [`TextField`](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/TextField/TextField.tsx#L268-L272), I'm passing `focused` onto `TextField` below

File: polaris-react/src/components/Filters/Filters.tsx [hunk 2]
```diff
@@ -91,6 +91,8 @@ export interface FiltersProps {
   disableFilters?: boolean;
   /** Whether the text field should be borderless. Should be true when used as part of the IndexFilters component. */
   borderlessQueryField?: boolean;
+  /** Prefix SearchMinor icon on query field. */
+  showQueryIcon?: boolean;
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/Filters.tsx]: Screenshot 2023-11-21 at 4 33 01 PM

File: polaris-react/src/components/Filters/components/SearchField/SearchField.tsx [hunk 3]
```diff
@@ -57,52 +50,29 @@ export function SearchField({
...
-        onBlur={onBlur}
-        autoComplete="off"
-        placeholder={placeholder}
-        disabled={disabled}
-      />
-      {loading || value !== '' ? (
-        <div className={styles.Suffix}>
-          <InlineStack gap="200">
-            {loading ? (
-              <div className={styles.Spinner}>
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/components/SearchField/SearchField.tsx:84]: Spinner gets ported over to `TextField` via the `suffix` prop.

File: polaris-react/src/components/Filters/components/SearchField/SearchField.tsx [hunk 4]
```diff
@@ -57,52 +50,29 @@ export function SearchField({
...
-            {value !== '' ? (
-              <UnstyledButton
-                className={classNames(
-                  styles.ClearButton,
-                  focused && styles['ClearButton-focused'],
-                )}
-                onClick={() => handleClear()}
-                disabled={disabled}
-              >
-                <Text as="span" visuallyHidden>
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/components/SearchField/SearchField.tsx:97]: the clear button gets ported over to `TextField` via the `clearButton` prop. This code is nearly identical to what is already in [`TextField`](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/TextField/TextField.tsx#L357-L372). There are also bugs with this current custom implementation

File: polaris-react/src/components/TextField/TextField.scss [hunk 5]
```diff
@@ -23,13 +23,15 @@ $spinner-icon-size: 12px;
...
     .ClearButton {
+      display: block;
       visibility: visible;
       opacity: 1;
     }
   }
 
   &:not(:focus-within) {
     .ClearButton {
+      display: none;
```
Comment (sophschneider) [inline polaris-react/src/components/TextField/TextField.scss:34]: This solves the bug where the clear button is rendering when invisible and when the `TextField` is not focused

|Before|After|
|-|-|
|Screen Recording 2023-11-21 at 5 04 49 PM|Screen Recording 2023-11-21 at 5 03 34 PM|

File: polaris-react/src/components/TextField/TextField.tsx [hunk 6]
```diff
@@ -164,7 +164,7 @@ interface NonMutuallyExclusiveProps {
   /** Visual styling options for the TextField
    * @default 'inherit'
    */
-  variant?: 'inherit' | 'borderless';
+  variant?: 'inherit' | 'borderless' | 'slim' | 'borderlessSlim';
```
Comment (sophschneider) [inline polaris-react/src/components/TextField/TextField.tsx]: Lmk if this api choice is ok. We could also create a new boolean prop called `inTable` or something to make the use case more specific and use it with `variant='borderless'`.

|Option 1 (this PR)|Option 2|Option 3|
|-|-|-|
|`<TextField variant='borderlessSlim' />`|`<TextField variant='borderless' inTable />`|Keep custom text field implementation in `Filters`|

File: polaris-react/src/components/TextField/TextField.scss [hunk 7]
```diff
@@ -249,6 +251,23 @@ $spinner-icon-size: 12px;
...
+}
+
+.slim {
+  .Input,
+  .Backdrop {
+    min-height: 28px;
+    padding-block: var(--p-space-050);
+  }
+}
+
```
Comment (sophschneider) [inline polaris-react/src/components/TextField/TextField.scss:270]: Note `Filters` search field height:
|-|medium and up screens|small screens|
|-|-|-|
|[Production](https://storybook.polaris.shopify.com/?path=/story/all-components-filters--with-a-resource-list)|`28px`|`28px`|
|[Figma](https://www.figma.com/file/jLLkmo9r28hiqPvf4s90E4/Polaris-Gen-3-Components?type=design&node-id=67128%3A21676&mode=design&t=0yMmrHC8rlYKmHQq-1)|`28px`|`36px`|
|This PR|`28px`|`28px`|

let me know if I should add a different height for small screens here. `36px` seemed drastically bigger than what is in production today but we can always update

File: polaris-react/src/components/TextField/TextField.tsx (hunk 6 above)
Comment (sarahill) [reply polaris-react/src/components/TextField/TextField.tsx]: Another potential option is to add a `size` property for `slim` (or whatever convention we want to use-sizing needs some work across the board but this may not be the place to flesh that out). Then I could combine the size and wether or not it has a border. Unless the concern/thought is we only want this combination in a really specific context.

File: polaris-react/src/components/TextField/TextField.scss (hunk 7 above)
Comment (sarahill) [reply polaris-react/src/components/TextField/TextField.scss:270]: I can update Figma to match the `28px` on both desktop and mobile. We've refactored all the Figma components but that work is still on a branch so I'll make the update there and it will be reflected in the main kit once merged (next week).

File: polaris-react/src/components/Filters/Filters.tsx (hunk 2 above)
Comment (LA1CH3) [reply polaris-react/src/components/Filters/Filters.tsx]: Curious for your thoughts on just making this more open and instead allowing something like `queryFieldPrefix` to allow for any potential prefix. I know right now the only use case is a search icon, and considering this is a search field, 9/10 times it would probably get used with `SearchMinor` but this could allow for flexibility in the future. 

However, maybe we intentionally want to constrain this to using `SearchMinor` for consistent search experiences?

File: polaris-react/src/components/Filters/components/SearchField/SearchField.tsx [hunk 8]
```diff
@@ -57,52 +50,29 @@ export function SearchField({
...
-              </UnstyledButton>
-            ) : null}
-          </InlineStack>
-        </div>
-      ) : null}
-    </div>
+    <TextField
+      id={id}
+      value={value}
+      onChange={(event) => handleChange(event ?? value)}
```
Comment (LA1CH3) [inline polaris-react/src/components/Filters/components/SearchField/SearchField.tsx]: Nit but I believe `TextField.onChange` will only pass the value, so the naming of `event` may be misleading here?

File: polaris-react/src/components/Filters/components/SearchField/SearchField.tsx [hunk 9]
```diff
@@ -57,52 +50,29 @@ export function SearchField({
...
+      prefix={showQueryIcon ? <Icon source={SearchMinor} /> : undefined}
+      suffix={
+        loading ? (
+          <div className={styles.Spinner}>
+            <Spinner size="small" />
+          </div>
+        ) : null
+      }
+      focused={focused}
+      label=""
```
Comment (LA1CH3) [inline polaris-react/src/components/Filters/components/SearchField/SearchField.tsx]: Is this ok to have an empty `label` or should we perhaps pass `placeholder`?

**Review by LA1CH3 — APPROVED** [review]

File: polaris-react/src/components/Filters/Filters.tsx (hunk 2 above)
Comment (sophschneider) [reply polaris-react/src/components/Filters/Filters.tsx]: yeah I think making the experiences consistent with only the search icon makes sense for now, but we can extend in the future if needed!

File: polaris-react/src/components/TextField/TextField.tsx (hunk 6 above)
Comment (sophschneider) [reply polaris-react/src/components/TextField/TextField.tsx]: that makes sense to me! I'll align it to what we have in `Button`, both `variant` and `size`

File: polaris-react/src/components/Filters/Filters.tsx (hunk 2 above)
Comment (sophschneider) [reply polaris-react/src/components/Filters/Filters.tsx]: @davidlng just shared [this issue](https://github.com/Shopify/web/issues/108834) with me, I'm think I'll just remove this prop and build it in for all tables again since it was just removed for IndexFilters anyways and if they want to add it back in we can add it back in everywhere

**Review by sarahill — APPROVED** [review]
✅

File: polaris-react/src/components/Filters/Filters.scss [hunk 10]
```diff
@@ -9,19 +9,10 @@
   background: var(--p-color-bg-surface);
 }
 
-.ContainerUplift {
-  background: none;
-}
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/Filters.scss:14]: @mrcthms I removed [this style](https://github.com/Shopify/polaris/pull/10343/files#diff-4314b26ffe17ad53260708e9c108fcb4eb85feae06bfa30daf785346a3a7f549R12-R14) since it was causing a transparent sticky container on mobile, let me know if it was needed for something else! 

|Before|After|
|-|-|
|Screenshot 2023-11-23 at 3 10 31 PM|Screenshot 2023-11-23 at 3 59 09 PM|

File: polaris-react/src/components/IndexFilters/IndexFilters.tsx [hunk 11]
```diff
@@ -366,6 +366,7 @@ export function IndexFilters({
                       xs: '0',
                       md: '200',
                     }}
+                    wrap={false}
```
Comment (sophschneider) [inline polaris-react/src/components/IndexFilters/IndexFilters.tsx:369]: This was fixes a bug with the sticky header measurer on mobile since it was wrapping the tabs/search on first render

|Before|After|
|-|-|
|Screenshot 2023-11-23 at 3 22 32 PM|Screenshot 2023-11-23 at 3 22 40 PM|

File: polaris-react/src/components/Filters/Filters.tsx [hunk 12]
```diff
@@ -123,21 +122,10 @@ export function Filters({
...
-    paddingBlockStart: '200',
-    paddingBlockEnd: '200',
-  };
-
+  const hideFilterBar = hideFilters || filters.length === 0;
   const queryFieldMarkup = hideQueryField ? null : (
-    <div className={classNames(styles.Container, styles.ContainerUplift)}>
-      <Box {...containerSpacing}>
+    <div className={styles.Container}>
+      <Box padding={hideFilterBar ? '300' : '200'}>
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/Filters.tsx:128]: This aligns the query field with the table content when the filter bar doesn't exist 
Screenshot 2023-11-23 at 3 41 20 PM

File: polaris-react/src/components/Filters/Filters.scss [hunk 13]
```diff
@@ -52,7 +43,7 @@
 .FiltersInner {
   overflow: auto;
   white-space: nowrap;
-  padding: var(--p-space-300) var(--p-space-400) var(--p-space-500);
+  padding: var(--p-space-300) var(--p-space-200) var(--p-space-500);
```
Comment (sophschneider) [inline polaris-react/src/components/Filters/Filters.scss:46]: align the filter bar to the search bar on mobile

|Before|After|
|-|-|
|Screenshot 2023-11-23 at 4 00 35 PM|Screenshot 2023-11-23 at 4 01 12 PM|

**Review by dGoligorsky — APPROVED** [review]
Looks great! Thank youuu!
I also really like how you add comments to the PR conversation highlighting the code that makes the changes 🙏
