### PR TITLE
[Skip to content] Fix tabIndex issue

### LINKED ISSUE #1816: v3.19.0 interop regression in web
After deploying v3.19.0 to web we had to revert it in https://github.com/Shopify/web/pull/15881 thanks to issues with the Rails admin interop stuff.

Various rails-based popovers failed to honor what you click on. You can see this in action:

In web: `git checkout 7b9097da` (the last commit with polaris v3.19.0, before the revert)
Run `yarn run sk clean` to make sure you've got no old build remnants lieing around
Edit the `plugins.vendor` section of sewing-kit.config.ts, commenting out the "@shopify/polaris" line so that the polaris tooling doesn't get included in the vendor bundle.

Run `dev server` then go to the existing product and add some "tag1" and "tag2" as tags.
Then go to the add a new product page and try and add one of those new tags to the product by typing "t" in the tags box, and try to click on the "tags1" item in the popover that appears.

The popover closes without adding the tag.

Expected behaviour: the tag is selected.

---

I've spent the day trying to work out what causes this through slow elimination I've gotten quite close but don't have a smoking gun. Here's how to test a given polaris-react commit within web, so we can work out what commit causes the problem.

- Stop your web `dev` server.
- In polaris-react: Run`git checkout f2389d0d` (/whatever commit you want to test) then do `yarn run build-consumer web` to push this into web's node_modules.
- In web: Run `yarn run sk clean && dev server` and follow the above steps to try and add a tag and see if it works.

I've confirmed f2389d0d works as expected for me and there's only commits from two PRs between that and v3.19.0 left https://github.com/Shopify/polaris-react/compare/f2389d0d7...v3.19.0

Happy hunting

### PR DESCRIPTION
**Pull request by dleroux**
### WHY are these changes introduced?

In this PR: https://github.com/Shopify/polaris-react/pull/1785 We added focus to the `<main>` element by adding tabIndex={-1}. This broke the Polaris-rails popover. In rails clicking the popover sends the target and hides the popover if the target isn't inside a popover. Adding the tabIndex on the main element made it the target, therefore always closed the popover.

Fixes #1816

### WHAT is this pull request doing?

Adding an `<a>` tag at the beginning of the content and focusing it instead.

## 

### How to 🎩

To test this properly it is best to do it web.

1. Start web
2. In polaris-react: `yarn build-consumer web`.
3. Tab to the skip to content link and click it. You should skip to the content. Also, use voice over to ensure the correct text is being read.

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {Page} from '@shopify/polaris';

interface State {}

export default class Playground extends React.Component<never, State> {
  render() {
    return (
      <Page title="Playground">
        {/* Add the code you want to test here */}
      </Page>
    );
  }
}
```

</details>

### 🎩 checklist

* [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
* [ ] Updated the component's `README.md` with documentation changes
* [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: src/components/Frame/Frame.tsx [hunk 1]
```diff
@@ -246,6 +247,15 @@ class Frame extends React.PureComponent<CombinedProps, State> {
         />
       ) : null;
 
+    const skipToMainContentTarget = (
+      // eslint-disable-next-line jsx-a11y/anchor-is-valid
+      <a
+        id={APP_FRAME_MAIN_ANCHOR_TARGET}
+        ref={this.skipoToMainContentTargetNode}
```
Comment (jgodson) [inline src/components/Frame/Frame.tsx]: `skipoToMainContentTargetNode` extra `o` in here
