### PR TITLE
[ActionMenu] Fix type sharing between MenuAction and MenuGroup.actions

### LINKED ISSUE #1889: badge or helpText not displayed for Page secondaryActions
## Issue summary

badge or helpText does not display in a Page's secondaryActions

See sandbox
https://codesandbox.io/embed/nameless-cookies-mn2e8

### PR DESCRIPTION
**Pull request by chloerice**
### WHY are these changes introduced?

Fixes #1889

When the actions from `Page` `Header` were extracted into a separate component called `ActionMenu`, the types of `Page.secondaryActions` and `Page.actionGroups.actions` were accidentally combined into a single type called `MenuActionDescriptor`. Properties like `badge` and `helpText` are only supported in the items of action lists (which `actionGroups` render as).

### WHAT is this pull request doing?

Fixing the types for `MenuAction` and `MenuGroup` to align with `Page.secondaryActions` and `Page.actionGroups` again.

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

- Tests are all ✅?
- Playground and Page examples working as expected?

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import * as React from 'react';
import {DuplicateMinor, ViewMinor} from '@shopify/polaris-icons';
import {Page} from '../src';

interface State {}

export default class Playground extends React.Component<{}, State> {
  render() {
    return (
      <Page
        breadcrumbs={[{content: 'Products', url: '/products'}]}
        title="Jar With Lock-Lid"
        secondaryActions={[
          {
            icon: DuplicateMinor,
            content: 'Duplicate',
          },
          {icon: ViewMinor, content: 'View on your store'},
        ]}
        actionGroups={[
          {
            title: 'Promote',
            actions: [
              {
                badge: {content: 'New', status: 'new'},
                helpText: 'Something informative about this new action',
                content: 'New action',
                onAction: () => {},
              },
            ],
          },
        ]}
      />
    );
  }
}
```

</details>

### 🎩 checklist

* [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
* [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
* [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx [hunk 1]
```diff
@@ -9,14 +9,14 @@ import MenuAction from '../MenuAction';
...
+  /** Visually hidden menu description for screen readers */
   accessibilityLabel?: string;
-  /** Show or hide the MenuGroup */
+  /** Whether or not the menu is open */
   active?: boolean;
   /** Callback for opening the MenuGroup by title */
   onOpen(title: string): void;
   /** Callback for closing the MenuGroup by title */
-  onClose(): void;
+  onClose(title: string): void;
```
Comment (AndrewMusgrave) [inline src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx]: Curious why are we passing the title `onClose`? Was this previous functionality?

Comment (chloerice) [reply src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx]: Yes, this was the function signature before #1653

Comment (AndrewMusgrave) [reply src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx]: Gotcha, makes sense 😄
