### PR TITLE
[TextField] Allow click event on spinner (stepper in number type) 

### LINKED ISSUE #6725: [TextField]: Events no longer bubble up for Spinner (type='number')
## Issue summary

Click events do not bubble for the `Spinner`[(see here)](https://github.com/Shopify/polaris/blob/5981b1ba3b972f41a787d51e9881faccf7cd467c/polaris-react/src/components/TextField/TextField.tsx#L403) portion of the Textfield.  The spinner is the 🔼 and 🔽 when the `type='number'`.  This is problematic for when we need to implement onClick events around the TextField. This current [monorail schema](https://github.com/Shopify/monorail/blob/062ccd893702ef5804ebd36022d7d43666564429/schemas/admin_product_inventory_available_save_button_click/1.0.yml) measures whether or not a merchant used the stepper / spinner to adjust their inventory quantity. The `event.stopPropagation()` no longer allows us to capture this data 😢 and will always return false. 

## Expected behavior

Events triggered from the `<TextField />`'s stepper ("spinner") should bubble up.

## Actual behavior

Events triggered from the `<TextField />`'s stepper ("spinner") no longer bubble up.

## Steps to reproduce the problem

See the reduced test case.

## Reduced test case

**Current behaviour**  https://codesandbox.io/s/textfield-events-polaris-9-12-0-forked-vkje4z?file=/App.js:0-565

1. Open the console
2. Click on the text field stepper
3. See that the event does not get consoled out (when the stepper is used)
4. Click inside the input portion of the text field
5. Notice that the event _does_ get consoled out (when you solely click on the input)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 9.19.0 (https://github.com/Shopify/web/blob/ecf2d284ddeba49fb4bdd8650d4d84f235459264/package.json#L142)
- Browser: Chrome
- Device: Macbook Pro
- Operating System: macOS 12.5

### PR DESCRIPTION
**Pull request by ginabak**
co-author: @weslleyaraujo 
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/6725
Part of https://github.com/Shopify/inventory-states-ux/issues/524
Follow up to https://github.com/Shopify/polaris/pull/6129 https://github.com/Shopify/web/pull/68974

As of Polaris 9.12.0, we no longer bubble up click events emitted on `TextField` and parent elements can no longer depend on interactions. This change was introduced [here](https://github.com/Shopify/polaris/commit/e519016562c8caa70ae4e9e5210b660a0b9a112c#diff-b3c67fa075f17d88f8c43be7df7456856ae03cb49912c84f23560ddaf30d4fa4R632). 

Click events do not bubble for the `Spinner`[(see here)](https://github.com/Shopify/polaris/blob/5981b1ba3b972f41a787d51e9881faccf7cd467c/polaris-react/src/components/TextField/TextField.tsx#L403) portion of the Textfield.  The spinner is the 🔼 and 🔽 when the `type='number'`.  **_This is problematic for when we need to implement onClick events around the TextField_**. This current [monorail schema](https://github.com/Shopify/monorail/blob/062ccd893702ef5804ebd36022d7d43666564429/schemas/admin_product_inventory_available_save_button_click/1.0.yml) measures whether or not a merchant used the stepper / spinner to adjust their inventory quantity. The `event.stopPropagation()` no longer allows us to capture this data 😢 and will always return false. 

### WHAT is this pull request doing?

This PR will conditionally call stopPropagation when click events are captured by TextField and parent elements.

If it is either the `spinner` or an `input`, it will no longer call the `stopPropagation`. 

### BEFORE

https://user-images.githubusercontent.com/43223543/180799925-71a9ae49-105f-490b-a6e5-60c263e1805a.mp4

### AFTER

https://user-images.githubusercontent.com/43223543/180799916-97a90764-786a-4664-accb-6cf385ee804e.mp4

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';

import {Badge, Page, Stack, TextField} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <Stack vertical>
        <div
          onClick={(event) =>
            console.log('Propagated event for the stepper / Spinner', event)
          }
        >
          <TextField
            label="Working Stepper Event"
            autoComplete="off"
            type="number"
          />
        </div>
        <div
          onClick={(event) =>
            console.log('Propagated event / verticalContent', event)
          }
        >
          <TextField
            label="Vertical Content"
            autoComplete="off"
            verticalContent={<Badge>Buyer</Badge>}
          />
        </div>
      </Stack>
    </Page>
  );
}

```

</details>

There should be two `TextField`s rendered in your playground and one of them contains a `Badge` as its `verticalContent` prop.

- Open your console and click the spinner on the first `TextField`
- You should see a log indicating that the click event bubbled up to its parent 🥳 
- On the second `TextField` click directly on the `Badge` (not the input field)
- You should not see any logs indicating that the click event bubbled up (unless you clicked on the input field)

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -644,18 +606,66 @@ export function TextField({
...
-function normalizeAriaMultiline(multiline?: boolean | number) {
-  if (!multiline) return undefined;
+  function handleClearButtonPress() {
+    onClearButtonClick && onClearButtonClick(id);
+  }
 
-  return Boolean(multiline) || multiline > 0
-    ? {'aria-multiline': true}
-    : undefined;
+  function handleKeyPress(event: React.KeyboardEvent) {
```
Comment (ginabak) [inline polaris-react/src/components/TextField/TextField.tsx:615]: I just moved these functions to be alphabetical so it's easier to read/find. It shouldn't affect the `git blame` if I'm not mistaken? 🤞🏽

File: .changeset/late-turkeys-teach.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@shopify/polaris': major
+---
+
+Allow click events for spinner in [TextField]
```
Comment (ginabak) [inline .changeset/late-turkeys-teach.md:5]: spinner (so confusing, I know), is not the actual "loading" spinner,[ it's this component](https://github.com/Shopify/polaris/blob/5981b1ba3b972f41a787d51e9881faccf7cd467c/polaris-react/src/components/TextField/TextField.tsx#L403) that has a confusing name, which is the 🔼 and the 🔽  (the stepper) portion of the TextField.

**Review by weslleyaraujo — APPROVED** [review]
awesome! Nice to see this one coming together 🙂

**Review by LauraAubin — APPROVED** [review]
🎩 and code looks great!

File: polaris-react/src/components/TextField/TextField.tsx [hunk 3]
```diff
@@ -629,7 +591,7 @@ export function TextField({
   }
 
   function handleClickChild(event: React.MouseEvent) {
-    if (inputRef.current !== event.target) {
+    if (!isSpinner(event.target) && !isInput(event.target)) {
```
Comment (chloerice) [inline polaris-react/src/components/TextField/TextField.tsx:595]: Hey @ginabak 👋🏽 Thanks for raising this! I think you will need to also add `isSpinner` to the conditional on line 581 in the `handleClick` method to prevent the input focus toggle/flash with each click of the spinner.

Comment (ginabak) [reply polaris-react/src/components/TextField/TextField.tsx:595]: Hi hi @chloerice ! GOOD CATCH, OMG! Thank-you! 😄 !

**Review by chloerice — APPROVED** [review]
🚀
