### PR TITLE
Fix padding on AlphaFilter in IndexFilter when hideQueryField is true

### LINKED ISSUE #9101: [IndexFilter] Incorrect spacing when `hideQueryFilter={true}`
## Issue summary

With using filters only we are using prop `hideQueryField={true}`, the filters row is reducing height probably because there is no padding on the sort button.

## Expected behavior

There should be space between the sort button and table.

## Actual behavior

The sort button is flush with the table below.

<details>
  <summary>Demo of issue</summary>
  demo-index-filter
</details>

## Steps to reproduce the problem

1. Set the `hideQueryFilter` prop to true on the `IndexFilter` component

### PR DESCRIPTION
**Pull request by sam-b-rose**
### WHY are these changes introduced?

Fixes #9101

### WHAT is this pull request doing?

- Adds a bottom padding to `AlphaFilters` container
- Aligns the content center to the filter wrapper

<details>
<summary>Before</summary>
befre
</details>

<details>
<summary>After</summary>
after
</details>

### Tophat instructions

- Add the `hideQueryField` prop to the Default IndexFilters.stories.tsx` example
- Run Storybook with `yarn dev`

Also

- [Spin link](https://admin.web.hide-query-field.sam-rose.us.spin.dev/store/shop1/products?selectedView=all) using snapshot

Demo with fix in spin on Products page:

https://user-images.githubusercontent.com/11774595/235160159-3341d0c2-a653-482d-9d28-1c47d3c17243.mov

### CODE REVIEW

File: polaris-react/src/components/AlphaFilters/AlphaFilters.tsx [hunk 1]
```diff
@@ -360,7 +360,7 @@ export function AlphaFilters({
           </div>
         </div>
         {hideQueryField ? (
-          <Box paddingInlineEnd="2" paddingBlockStart="2">
+          <Box paddingInlineEnd="2" paddingBlockStart="2" paddingBlockEnd="2">
```
Comment (alllx) [inline polaris-react/src/components/AlphaFilters/AlphaFilters.tsx]: Tophatted in storybook and just spotted difference in right padding when toggling display filters:

https://user-images.githubusercontent.com/701295/235190504-103d59fb-1b27-4993-9dfa-0f9f84a04fa9.mov

```suggestion
          <Box paddingInlineEnd="3" paddingBlockStart="2" paddingBlockEnd="2">
```

Comment (sam-b-rose) [reply polaris-react/src/components/AlphaFilters/AlphaFilters.tsx]: Good catch! Thanks, @alllx!

**Review by alllx — APPROVED** [review]
LG 👍🏼

**Review by kyledurand — APPROVED** [review]
